// client/src/components/live/Live.tsx
"use client";

import { useEffect, useState } from "react";

const Live = () => {
  const [time, setTime] = useState("");

  useEffect(() => {
    const eventSource = new EventSource("http://localhost:4000/api/v1/live");

    eventSource.onopen = (event) => {
      console.log(event);
    };
    eventSource.onmessage = (e) => {
      setTime(e.data);
    };

    return () => eventSource.close();
  }, []);

  return (
    <>
      <h2 className="text-2xl">Live</h2>
      <p>{time}</p>
    </>
  );
};

export default Live;

// frontend/src/routes/live/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	let messages: { type: string; date: string } | undefined = $state();

	onMount(() => {
		const evtSource = new EventSource('http://localhost:3000/');
		evtSource.onopen = function (event) {
			console.log('open');
		};

		evtSource.onmessage = function (event) {
			messages = JSON.parse(event.data);
		};

		return () => {
			evtSource.close();
		};
	});
</script>

<svelte:head>
	<title>F1 Dashboard | Live</title>
</svelte:head>
{#if messages}
	<p>{messages?.type}</p>
	<p>{messages?.date}</p>
{/if}
