// frontend/src/lib/components/MediaControls.svelte
<script lang="ts">
	import { Play } from 'lucide-svelte';
</script>

<div class="absolute bottom-0 flex w-full items-center justify-stretch gap-1 p-1">
	<button class="aspect-square w-8 rounded-full bg-neutral-700">
		<Play fill="#fff" class="m-auto w-3.5 translate-x-[1px]" />
	</button>
	<select class="h-fit appearance-none rounded bg-neutral-700 px-2 py-0.5">
		<option>x1</option>
		<option>x2</option>
		<option>x4</option>
	</select>
	<input type="range" class="h-1 w-full appearance-none rounded bg-neutral-500/50 accent-white" />
	<p>00:00</p>
</div>

// client/src/components/MediaControls.tsx
"use client";
import { store } from "@/store/";
import { SessionGp } from "@/types";
import { FaPlay, FaPause } from "react-icons/fa6";

const MediaControls = ({ sessionInfo }: { sessionInfo: SessionGp }) => {
  const {
    isPlaying,
    setTime,
    time,
    toggleIsPlaying,
    setMinute,
    setWasPlaying,
  } = store();
  const totalSeconds =
    new Date(sessionInfo.endDate).getTime() -
    new Date(sessionInfo.startDate).getTime();

  const changeTimeHandler = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (isPlaying) {
      toggleIsPlaying();
      setWasPlaying(true);
    }
    setTime(
      new Date(
        new Date(sessionInfo.startDate).getTime() + parseInt(e.target.value),
      ),
    );
  };
  const sizeHandler = () => {
    const minute = Math.floor(
      (time.getTime() - new Date(sessionInfo.startDate).getTime()) / 1000 / 60,
    );
    setMinute(minute);
  };

  return (
    <div className="absolute bottom-2 flex w-[calc(100%-2rem)] items-center gap-4">
      <button
        className="rounded-full bg-neutral-700 p-2 text-sm"
        onClick={() => toggleIsPlaying()}
      >
        {isPlaying ? <FaPause /> : <FaPlay className="translate-x-0.5" />}
      </button>

      <input
        type="range"
        min="0"
        max={totalSeconds}
        className="h-1 w-full appearance-none rounded bg-neutral-500 accent-white"
        value={time.getTime() - new Date(sessionInfo.startDate).getTime()}
        onChange={changeTimeHandler}
        onClick={sizeHandler}
      />

      <p className="text-sm">{`${time.toLocaleTimeString("en-GB")}`}</p>
    </div>
  );
};
export default MediaControls;
